server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/jugacionbd?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: user
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
